version: '3'
services:
  # --- 1. KAFKA & ZOOKEEPER ---
  zookeeper:
    image: 'zookeeper:3.7'
    ports:
      - '2181:2181'

  kafka:
    image: 'wurstmeister/kafka:2.13-2.8.1'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Crea tus topics automáticamente al arrancar
      KAFKA_CREATE_TOPICS: "flights_rt_api:1:1,weather_rt_api:1:1"
    depends_on:
      - zookeeper

  # --- 2. MOTOR FLINK (Donde Beam ejecutará el trabajo) ---
  jobmanager:
    image: apache/flink:1.16.0
    ports:
      - "8081:8081"
      - "6123:6123"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: apache/flink:1.16.0
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

  # --- 3. TU ENTORNO PYTHON (BEAM) ---
  beam-worker:
    build: .  # Usa el Dockerfile que creaste arriba
    volumes:
      - .:/app  # Conecta tu carpeta de Windows con el contenedor
    depends_on:
      - jobmanager
      - kafka